# fly.toml app configuration file generated for mplusback on 2023-10-25T15:35:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mplusback"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
